# Generated by Django 2.0 on 2019-07-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('exp_date', models.DateField()),
                ('reviews', models.CharField(max_length=50)),
                ('ratings', models.IntegerField()),
                ('return_policy', models.CharField(choices=[('YES', 'Y'), ('NO', 'N')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('name', models.CharField(max_length=30, primary_key='True', serialize=False)),
                ('address', models.TextField(max_length=50)),
                ('contact_no', models.BigIntegerField()),
                ('landmark', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='strore_id',
            field=models.ForeignKey(on_delete='CASCADE', related_name='store_products', to='products.Stores'),
        ),
    ]
