# Generated by Django 2.0 on 2019-07-08 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='ratings',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='return_policy',
            field=models.CharField(choices=[('YES', 'Y'), ('NO', 'N')], default='Y', max_length=5),
        ),
        migrations.AlterField(
            model_name='products',
            name='reviews',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_prod', to='products.Stores'),
        ),
    ]
